const catalogue = [
  // ─── CCTV PRODUCTS ───
  {
    id: 1,
    type: 'product',
    category: 'CCTV',
    name: 'Hikvision 4K Dome Camera',
    description: 'Indoor/outdoor dome camera with 4K resolution, built-in IR night vision up to 30m, and weatherproof IP67 casing. Ideal for offices, shops, and entrances.',
    image: 'https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=800&q=80',
    priceLabel: 'From Ksh 8,500',
    price: 8500,
    badge: 'Best Seller',
    available: true,
    specs: ['4K Resolution', '30m Night Vision', 'IP67 Weatherproof', 'Wide Angle 100°'],
  },
  {
    id: 2,
    type: 'product',
    category: 'CCTV',
    name: 'Hikvision PTZ Camera',
    description: 'Pan-tilt-zoom camera with 360° coverage and 30x optical zoom. Perfect for large compounds, parking lots, and warehouses requiring wide-area monitoring.',
    image: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800&q=80',
    priceLabel: 'From Ksh 22,000',
    price: 22000,
    badge: 'Premium',
    available: true,
    specs: ['360° Pan & Tilt', '30x Optical Zoom', '4K Resolution', 'Auto Tracking'],
  },
  {
    id: 3,
    type: 'product',
    category: 'CCTV',
    name: '8-Channel DVR Kit',
    description: 'Complete 8-channel DVR system with 2TB hard drive, HDMI output, and remote phone viewing via Hik-Connect app. Supports up to 8 cameras.',
    image: 'https://images.unsplash.com/photo-1562813733-b31f71025d54?w=800&q=80',
    priceLabel: 'From Ksh 18,000',
    price: 18000,
    badge: null,
    available: true,
    specs: ['8 Channels', '2TB Storage', 'Remote Viewing', 'Motion Alerts'],
  },

  // ─── SOLAR PRODUCTS ───
  {
    id: 4,
    type: 'product',
    category: 'Solar',
    name: 'Luminous 200W Solar Panel',
    description: 'KEBS certified monocrystalline solar panel with 25-year performance warranty. High efficiency in low-light conditions — ideal for Nairobi weather.',
    image: 'https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?w=800&q=80',
    priceLabel: 'From Ksh 16,000',
    price: 16000,
    badge: 'KEBS Certified',
    available: true,
    specs: ['200W Output', 'Monocrystalline', '25yr Warranty', 'High Efficiency'],
  },
  {
    id: 5,
    type: 'product',
    category: 'Solar',
    name: 'Luminous 200Ah Battery',
    description: 'Deep cycle tubular battery designed for solar systems. Long life cycle of 1,200+ charges and excellent performance in high-temperature environments.',
    image: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=800&q=80',
    priceLabel: 'From Ksh 28,000',
    price: 28000,
    badge: null,
    available: true,
    specs: ['200Ah Capacity', '1,200+ Cycles', 'Tubular Design', 'Low Maintenance'],
  },
  {
    id: 6,
    type: 'product',
    category: 'Solar',
    name: 'Schneider 3KVA Inverter',
    description: 'Pure sine wave inverter with built-in MPPT solar charge controller. Supports both solar and grid input with automatic switching.',
    image: 'https://images.unsplash.com/photo-1611365892117-00ac5ef43c90?w=800&q=80',
    priceLabel: 'From Ksh 45,000',
    price: 45000,
    badge: 'Premium',
    available: true,
    specs: ['3KVA Output', 'Pure Sine Wave', 'MPPT Controller', 'Auto Switching'],
  },

  // ─── ELECTRICAL PRODUCTS ───
  {
    id: 7,
    type: 'product',
    category: 'Electrical',
    name: 'Schneider Distribution Board',
    description: '18-way consumer unit with surge protection and earth leakage circuit breaker. Suitable for residential and light commercial applications.',
    image: 'https://images.unsplash.com/photo-1621905251189-08b45249ff78?w=800&q=80',
    priceLabel: 'From Ksh 12,000',
    price: 12000,
    badge: null,
    available: true,
    specs: ['18-Way Board', 'Surge Protection', 'ELCB Included', 'ERC Compliant'],
  },

  // ─── CCTV SERVICES ───
  {
    id: 8,
    type: 'service',
    category: 'CCTV',
    name: 'Home CCTV Installation',
    description: 'Complete CCTV setup for your home. We handle everything — site survey, camera placement, cabling, DVR configuration, and phone setup.',
    image: 'https://images.unsplash.com/photo-1616261167032-b16d2df8333b?w=800&q=80',
    priceLabel: 'From Ksh 25,000',
    price: 25000,
    badge: 'Most Popular',
    available: true,
    specs: null,
    includes: [
      '4 HD cameras supplied & installed',
      'DVR + 1TB storage included',
      'Professional cabling & routing',
      'Remote phone viewing setup',
      '1 year workmanship warranty',
    ],
  },
  {
    id: 9,
    type: 'service',
    category: 'CCTV',
    name: 'Business CCTV Package',
    description: 'Full security camera solution for offices, shops, and warehouses. Includes NVR system, HD cameras, and 24/7 remote monitoring capability.',
    image: 'https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=800&q=80',
    priceLabel: 'From Ksh 55,000',
    price: 55000,
    badge: null,
    available: true,
    specs: null,
    includes: [
      '8 cameras supplied & installed',
      'NVR + 2TB storage included',
      'Structured cabling throughout',
      'Staff access control optional',
      '1 year full support',
    ],
  },

  // ─── SOLAR SERVICES ───
  {
    id: 10,
    type: 'service',
    category: 'Solar',
    name: 'Home Solar System',
    description: 'Custom solar power system designed for your home energy needs. Includes load analysis, system design, supply, and full installation.',
    image: 'https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?w=800&q=80',
    priceLabel: 'From Ksh 85,000',
    price: 85000,
    badge: 'Most Popular',
    available: true,
    specs: null,
    includes: [
      'Free site & load analysis',
      '2x 200W panels + batteries',
      '2KVA inverter included',
      'Full installation & wiring',
      '2 year maintenance support',
    ],
  },

  // ─── ELECTRICAL SERVICES ───
  {
    id: 11,
    type: 'service',
    category: 'Electrical',
    name: 'Full House Wiring',
    description: 'Complete electrical wiring for new constructions or full rewiring of existing buildings. All work done to ERC standards with certified technicians.',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    priceLabel: 'From Ksh 40,000',
    price: 40000,
    badge: null,
    available: true,
    specs: null,
    includes: [
      'Full wiring & conduit work',
      'Distribution board supply & fit',
      'ERC-compliant installation',
      'Safety inspection certificate',
      '1 year workmanship warranty',
    ],
  },
  {
    id: 12,
    type: 'service',
    category: 'Electrical',
    name: 'Emergency Electrical Repair',
    description: 'Fast-response electrical repairs for faults, outages, and safety hazards. Available across Nairobi with same-day response.',
    image: 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=800&q=80',
    priceLabel: 'From Ksh 3,500',
    price: 3500,
    badge: '24/7 Available',
    available: true,
    specs: null,
    includes: [
      'Same-day response',
      'Fault diagnosis included',
      'Genuine parts used',
      'Safety check after repair',
    ],
  },
]

export default catalogue
